""" Collision Checker takes the lattice graphs generated by Lattice Generator and modifies it 
based on the predicted subject path from Subject Predictor and the CARLA road environment. """
from carla import *
import numpy as np

class CollisionChecker:
    def __init__(self):

        self.lattice_graph = None
        self.subject_path = None
    
    def predict_collision(self, ego, subject):
        collide = false
        for ego_pos in self.lattice_graph:
            for sub_pos in self.subject_path:
                collide = check_collision(ego, subject, ego_pos, sub_pos)
        
        return collide

    def check_collision(self, ego, subject, ego_pos, sub_pos):
        sep_ax = false
        if ego_pos[0] + ego.bounding_box.extent.x < subject_pos[0] - subject.bounding_box.extent.x or \
            ego_pos[0] - ego.bounding_box.extent.x > subject_pos[0] + subject.bounding_box.extent.x:
            sep_ax = true
        
        if ego_pos[1] + ego.bounding_box.extent.y < subject_pos[1] - subject.bounding_box.extent.y or \
        ego_pos[1] - ego.bounding_box.extent.y > subject_pos[1] + subject.bounding_box.extent.y:
            sep_ax = true

        return not sep_ax

    def update_lattice(self, lattice_graph):
        self.lattice_graph = lattice_graph

    def update_subject_path(self, subject_path):
        self.subject_path = subject_path

    def assign_cost(self):
        pass
